apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: convtemp
  template:
    metadata:
      labels:
        app: convtemp
    spec:
      containers:
      - name: convtemp
        image: dellabeneta/convtemp:v2
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP