apiVersion: v1
kind: Service
metadata:
  name: conversao-temp
spec:
  selector:
    app: conversao-temp
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30000
